project:
  type: website
  output-dir: docs

website:
  title: "Daily Exercise 6 Spring 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    self-contained: true

editor: visual

