project:
  type: website
  output-dir: docs

website:
  title: "daily-exercise-6.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    self-contained: true

editor: visual

